# 线上配置文件
# @author <a href="https://github.com/liyupi">程序员鱼皮</a>
# @from <a href="https://www.code-nav.cn">编程导航</a>
server:
  port: 8101
  servlet:
    session:
      cookie:
        max-age: 2592000
        same-site: none
        secure: true
spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.1.100.190/yudada
    username: root
    password: Cqx06130316
  # Redis 配置
#  redis:
#    database: 1
#    host: 修改为你的地址
#    port: 6379
#    password: 修改为你的密码
  # 分库分表配置（开源代码部署可忽略）
  shardingsphere:
    #数据源配置
    datasource:
      # 多数据源以逗号隔开即可
      names: yudada
      yudada:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://10.1.100.190/yudada
        username: root
        password: Cqx06130316
    # 规则配置
    rules:
      sharding:
        # 分片算法配置
        sharding-algorithms:
          # 自定义分片规则名
          answer-table-inline:
            ## inline 类型是简单的配置文件里面就能写的类型，其他还有自定义类等等
            type: INLINE
            props:
              algorithm-expression: user_answer_$->{appId % 2}
        tables:
          user_answer:
            actual-data-nodes: yudada.user_answer_$->{0..1}
            # 分表策略
            table-strategy:
              standard:
                sharding-column: appId
                sharding-algorithm-name: answer-table-inline
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''
# 接口文档配置
#knife4j:
#  basic:
#    enable: true
#    username: 修改为你的用户名
#    password: 修改为你的密码